#!/usr/bin/env python3
r"""Oracle for the save-file chunk framing (scope PORT-C).

Entry points under test (all in LEGOLAND/profiles.c and LEGOLAND/saveprof.c):

    BeginMeasuredBlock  0x0047d790   push the offset of a 4-byte placeholder
    EndMeasuredBlock    0x0047d800   pop it, back-patch with the END offset
    SaveGameWrite       0x0047d760   _write(g_savefile_fd, ...) == n
    SaveGameRead        0x0047d730   _read(g_savefile_fd, ...)  == n
    FindeIneList        0x0047d880   element pointer -> index in g_elist

The contract (docs/runtime/persistence.md, and the header comment of
LEGOLAND/profiles.c "save-file chunk framing"): a measured block is a 4-byte
little-endian word holding the ABSOLUTE FILE OFFSET OF THE BLOCK'S END -- not
a byte count -- written as a zero placeholder on entry and back-patched on
exit, with `g_chunk_offsets` (0x006691bc) used as a stack so blocks nest.
That "absolute end offset, not a length" detail is the whole reason this is
worth a test: a reader that treats the word as a length walks off the file.

This oracle is NOT a decoder of shipped game data -- there is no .sav in
gamedata/ -- so it emits a deterministic SCRIPT of framing operations plus
the exact bytes the engine must produce for it. The C test replays the same
script through the game's own functions and compares. Nothing about the game's
assets appears in the output: a script, a size, a digest and the back-patched
words.

    python3 tools/oracle_savechunks.py --header <out.h>
    python3 tools/oracle_savechunks.py --json   <out.json>
"""
import argparse
import json
import struct
import sys

FNV_BASIS = 0xcbf29ce484222325
FNV_PRIME = 0x100000001b3
MASK64 = (1 << 64) - 1

OP_BEGIN = 0
OP_WRITE = 1
OP_END = 2

# Nesting to depth 4, sibling blocks, a zero-length block and an empty nest:
# every shape the engine's own chunk writers produce (savegame.c's per-block
# frames, savechunks.c's nested per-record frames).
SCRIPT = [
    (OP_BEGIN, 0),
    (OP_WRITE, 13),
    (OP_BEGIN, 0),                 # nested
    (OP_WRITE, 1),
    (OP_END, 0),
    (OP_BEGIN, 0),                 # sibling, empty
    (OP_END, 0),
    (OP_WRITE, 257),               # crosses a 256-byte payload wrap
    (OP_BEGIN, 0),
    (OP_BEGIN, 0),
    (OP_BEGIN, 0),                 # depth 4
    (OP_WRITE, 4),
    (OP_END, 0),
    (OP_WRITE, 2),
    (OP_END, 0),
    (OP_END, 0),
    (OP_END, 0),
    (OP_WRITE, 8),                 # after the outermost block closed
]

# g_elist for the FindeIneList probes: the save file refers to LLIDB elements
# by index into this list, and -1 means "not on the list" (with the caller's
# `assigned` flag cleared).  Values are arbitrary tokens, not game data.
ELIST = [0x11110000, 0x22220000, 0x33330000, 0x44440000, 0x55550000]
ELIST_PROBES = [0x33330000, 0x11110000, 0x55550000, 0x66660000, 0]


def fnv(data):
    h = FNV_BASIS
    for b in data:
        h = ((h ^ b) * FNV_PRIME) & MASK64
    return h


def run_script(script=SCRIPT):
    """Model BeginMeasuredBlock / SaveGameWrite / EndMeasuredBlock exactly."""
    buf = bytearray()
    pos = 0
    stack = []
    payload = 0          # running payload byte counter (the C test mirrors it)
    patches = []         # (placeholder offset, back-patched value)
    max_depth = 0

    def write(bs):
        nonlocal pos
        if pos > len(buf):
            buf.extend(b"\0" * (pos - len(buf)))
        buf[pos:pos + len(bs)] = bs
        pos += len(bs)

    for op, n in script:
        if op == OP_BEGIN:
            stack.append(pos)
            max_depth = max(max_depth, len(stack))
            write(b"\0\0\0\0")
        elif op == OP_WRITE:
            write(bytes((payload + i) & 0xff for i in range(n)))
            payload += n
        elif op == OP_END:
            end = pos
            at = stack.pop()
            buf[at:at + 4] = struct.pack("<i", end)
            patches.append((at, end))
            pos = end
        else:
            raise ValueError(op)
    if stack:
        raise AssertionError("script leaves %d block(s) open" % len(stack))
    return {
        "size": len(buf),
        "fnv": fnv(buf),
        "patches": patches,
        "max_depth": max_depth,
        "payload_bytes": payload,
        # Re-reading the whole file and hashing it is the SaveGameRead check.
        "read_back_fnv": fnv(buf),
    }


def expected_elist_results():
    """FindeIneList: returns 1 and rewrites *pval with the index, else 0/-1."""
    out = []
    for v in ELIST_PROBES:
        if v in ELIST:
            out.append((v, 1, ELIST.index(v)))
        else:
            out.append((v, 0, -1))
    return out


def emit_header(fh, r):
    w = fh.write
    w("/* GENERATED by tools/oracle_savechunks.py -- do not edit. */\n")
    w("#ifndef ORACLE_SAVECHUNKS_H\n#define ORACLE_SAVECHUNKS_H\n\n")
    w("#define ORACLE_SAVE_OP_BEGIN 0\n#define ORACLE_SAVE_OP_WRITE 1\n"
      "#define ORACLE_SAVE_OP_END   2\n\n")
    w("static const struct { int op; int n; } oracle_save_script[] = {\n")
    for op, n in SCRIPT:
        w("    { %d, %d },\n" % (op, n))
    w("};\n")
    w("#define ORACLE_SAVE_SCRIPT_N %d\n\n" % len(SCRIPT))
    w("#define ORACLE_SAVE_SIZE          %d\n" % r["size"])
    w("#define ORACLE_SAVE_FNV           0x%016xull\n" % r["fnv"])
    w("#define ORACLE_SAVE_READBACK_FNV  0x%016xull\n" % r["read_back_fnv"])
    w("#define ORACLE_SAVE_MAX_DEPTH     %d\n" % r["max_depth"])
    w("#define ORACLE_SAVE_PAYLOAD       %d\n\n" % r["payload_bytes"])
    w("/* back-patched placeholders, in EndMeasuredBlock order: "
      "{file offset, absolute end offset written there} */\n")
    w("static const struct { int at; int end; } oracle_save_patches[] = {\n")
    for at, end in r["patches"]:
        w("    { %d, %d },\n" % (at, end))
    w("};\n")
    w("#define ORACLE_SAVE_PATCH_N %d\n\n" % len(r["patches"]))
    w("static const int oracle_elist[] = {\n")
    for v in ELIST:
        w("    %d,\n" % struct.unpack("<i", struct.pack("<I", v))[0])
    w("};\n")
    w("#define ORACLE_ELIST_N %d\n\n" % len(ELIST))
    w("/* FindeIneList probes: {value in, return, *pval out} */\n")
    w("static const struct { int in; int ret; int out; } "
      "oracle_elist_probes[] = {\n")
    for v, ret, idx in expected_elist_results():
        w("    { %d, %d, %d },\n"
          % (struct.unpack("<i", struct.pack("<I", v))[0], ret, idx))
    w("};\n")
    w("#define ORACLE_ELIST_PROBE_N %d\n\n" % len(ELIST_PROBES))
    w("#endif\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--header")
    ap.add_argument("--json")
    args = ap.parse_args()
    r = run_script()
    if args.header:
        with open(args.header, "w") as fh:
            emit_header(fh, r)
    if args.json:
        with open(args.json, "w") as fh:
            json.dump({k: (v if k != "fnv" and k != "read_back_fnv"
                           else "0x%016x" % v) for k, v in r.items()},
                      fh, indent=1)
    if not args.header and not args.json:
        json.dump({"size": r["size"], "fnv": "0x%016x" % r["fnv"],
                   "max_depth": r["max_depth"],
                   "payload_bytes": r["payload_bytes"],
                   "patches": r["patches"]}, sys.stdout, indent=1)
        print()


if __name__ == "__main__":
    main()
